[project]
name = "rag"
version = "0.1.0"
description = "RAG learning notes, notebooks, and mini-projects"
readme = "README.md"
authors = [
    { name = "amroosha", email = "amroshaa49@gmail.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "chromadb>=1.5.9",
    "langchain>=1.4.2",
    "langchain-community>=0.4.2",
    "langchain-groq>=1.1.3",
    "langchainhub>=0.1.21",
    "tiktoken>=0.14.0",
]




